Website update/maintenance - Dev branch pull request
adelaideblockchain/adelaideblockchain.github.io pull request #3
Opened 2018-09-23 15:00 UTC by ivanzinho09

Performing a pull request to try and get this website maintenance and upgrade move faster!
Please provide feedback on the work done so far, and what still needs to be added.

2018-09-23 15:31 UTC, ivanzinho09 commented
**Note:** There seems to be a conflict with the read me file, and it might be the fact that it is 1 AM, but I tried to fix it in my git terminal, but haven't been able to figure it out.

2018-09-23 15:34 UTC, JJ11teen commented
I can look into the conflict tomorrow, don't worry. I'll spend some time reviewing too.

2018-09-23 15:35 UTC, JJ11teen commented
Linking #2

2018-09-23 15:46 UTC, ivanzinho09 commented
@JJ11teen , I ended up solving it, I think :) 
Excited for the feedback tomorrow!

2018-09-24 06:57 UTC, JJ11teen commented
I started adding some code linting issues but I think in general there are more important dev chore things:

* folder structure should follow a standard (usually /js /styles and /assets directories, with html in root
* files need to be meaningfully named (eg background png), and follow consistent (usually camel) casing
* add a readme file documenting external libraries being used and why/what for

From a usability perspective:

* The 'sponsors' tab on the navbar has a larger highlight area than the other tabs
* mobile support needs work, padding missing around text and buttons not aligned
* white text is difficult to read over background with certain alignments
* social media buttons overlap sponsors on small screens

2018-10-02 08:23 UTC, JJ11teen requested changes
Small nits along with larger issues commented earlier. Seems some file directory stuff has been fixed by now though which is good. A readme explaining the libraries is a must however.

2018-10-02 08:23 UTC, JJ11teen commented on About.html
> +                                <p style="font-size: 1.2em;"><strong>Blockchain</strong> is a technology that provides true peer-to-peer transfer of value. It removes the need to trust intermediaries
These inline font sizes should be moved to stylesheet

2018-10-02 08:23 UTC, JJ11teen commented on About.html
> +                                <p style="font-size: 1.2em;"><strong>Blockchain</strong> is a technology that provides true peer-to-peer transfer of value. It removes the need to trust intermediaries
In general all of the inline styles should be moved to stylesheet

2018-10-02 14:58 UTC, nerd-1 commented on About.html
> +                                <p style="font-size: 1.2em;"><strong>Blockchain</strong> is a technology that provides true peer-to-peer transfer of value. It removes the need to trust intermediaries
Good idea, I'll move 'em across.

2018-10-02 15:18 UTC, nerd-1 commented
On the subject of the read me: There's a few libraries that are not currently in use and will probably never be used (i.e. wow.js, simplyCountdown ect.). Should I just say that they are unused or would It be worth deleting them altogether?

2018-10-02 16:01 UTC, ivanzinho09 commented
Awesome work on the changes to the file and folder structure and the updated about section, @nerd-1 !

The social media icons you fixed in the sponsor's page though, whilst looking better for tablet and desktop users, unfortunately do not function properly for the mobile version of the website (from testing done this afternoon). 

> On the subject of the read me: There's a few libraries that are not currently in use and will probably never be used (i.e. wow.js, simplyCountdown ect.). Should I just say that they are unused or would It be worth deleting them altogether?

I think that for now, mainly focusing on the layout and adding in content would be probably the better. In the future though and just in general, if we are not going to use them, might as well delete them. Don't stress too much over it for now though :)

2018-10-02 22:05 UTC, paulpounendis commented
Good work guys, I will plan to do some graphic design changes today. I pesonally hate the font haha ... If we can get the resources page up I can start going along and chucking some content in.

2018-10-02 22:54 UTC, JJ11teen commented
@nerd-1 deleting if they are unused would be great. 
Sorry @ivanzinho09 but I've got to disagree with your comment on current focus. A readme doc is invaluable in increasing development productivity and should be prioritised appropriately. Content and style are important, but a readme should document global styles and patterns used and result and faster turn around on a more functional, more consistent product here.

2018-10-03 03:50 UTC, paulpounendis commented
As a fyi, I am looking to eventually get the UI looking super clean. I can make it alot nicer, and will plan to make it have the same impact as this site for example. 

https://tenzorum.org/

2018-10-03 06:38 UTC, ivanzinho09 commented
> Sorry @ivanzinho09 but I've got to disagree with your comment ....

Fair enough, actually. That does seem like a better and more consistent method of working on things. Let's get do it that way instead then :)

2018-10-04 16:30 UTC, ivanzinho09 commented
@nerd-1, the page keeps getting better and better! Sorry I haven't been able to actively develop a lot more for it, but I will likely change up the contact section (whenever I can!!) to the one we already have set up in our dreamhost-surveymonkey account ;) It just looks a bit cleaner aha.

Reference for layout and theme scheme: 
https://puu.sh/BFDf2/27686c4434.png

2019-02-11 16:34 UTC, merged